[package]
name = "rock_run"
description = "Rock Run: Rose's odyssey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.2", features = [
  "wayland",
  "dynamic_linking",
] } # dynamic linking must be removed for release or wasm
bevy_ecs_tilemap = { path = "../bevy_ecs_tilemap" }
bevy_rapier2d = "0.25.0"
raqote = { version = "0.8.3", default-features = false, features = [
  "pathfinder_geometry",
] }
thiserror = "1.0.58"
tiled = { version = "0.11.2", default-features = false }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dev-dependencies]
pretty_assertions = "1.4.0"

[target.wasm32-unknown-unknown]
# export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-server-runner
# cargo run --target wasm32-unknown-unknown
# above lines work, however below directive does not work
runner = "wasm-server-runner"
