[target.wasm32-unknown-unknown]
# export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-server-runner
# cargo run --target wasm32-unknown-unknown
# above lines work, however below directive does not work
runner = "wasm-server-runner"
